# Usar la imagen oficial de Python 3.9 como base
FROM python:3.9

# Establecer el directorio de trabajo en /app
WORKDIR /app

# Copiar el archivo requirements.txt a la imagen
COPY config/requirements.txt .
COPY config/requirements_gui.txt .

# Instalar las dependencias
RUN pip install -r requirements.txt

# Para la interfaz grafica utilizo Xming
RUN config/requirements_gui.txt

# Copiar el código fuente de la aplicación a la imagen
COPY . .

# Exponer el puerto 5000
EXPOSE 5000

# Iniciar la aplicación
CMD ["python", "src/main.py"]





##############################################################
##############################################################
#  Crear imagen
#docker build -t gui_image .

# Ejecutar contenedor
#set DISPLAY=ip:0.0
#XmingXming.exe -ac
#docker run -it --rm -e DISPLAY=%DISPLAY% --network="host" --name gui_container gui_image

##############################################################
##############################################################
