version: "3.9"
services:
  mi_app_python:
    build: 
      context: .
      dockerfile: Dockerfile_python
    depends_on:
      - mi_app_mysql

  mi_app_mysql:
    build: 
      context: .
      dockerfile: Dockerfile_mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD: "root"
      #- MYSQL_USER: "root"
      # MY_SQL_PASSWORD: "root"
      #- MYSQL_DATABASE: "name"

# Generar Volumes