version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    network_mode: "host"
    restart: always

  python:
    build:
      context: .
      dockerfile: Dockerfile_python
    network_mode: "host"
    environment:
      - DISPLAY=DIRECCION_IP:0.0
    command: python src/main.py
