#services:
#  pythonapp:
#    build: ./python/
#    command: sh -c "sleep 10s ; python3 ./main.py"


version: "3.9"
services:
  mi_app_python:
    build: .
    ports:
      -"3000:3000"
    links:
      - mi_app_mysql

  mi_app_mysql:
    build: .
    ports:
      -"3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD: "root"